services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sp4rk
      - POSTGRES_USER=spark_user
      - POSTGRES_DB=spark